name: Compile Revit plugin

on:
  workflow_call:
    inputs:
      infrastructure_ref:
        description: "Git ref of revit-build-infrastructure to use"
        required: false
        type: string
        default: main

jobs:
  compile:
    runs-on: windows-2025
    steps:
      - name: Checkout plugin
        uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Checkout infrastructure
        uses: actions/checkout@v6
        with:
          repository: Abstrakcionist/revit-build-infrastructure
          ref: ${{ inputs.infrastructure_ref }}
          path: .infrastructure
          fetch-depth: 0
          token: ${{ secrets.INFRA_ACCESS_TOKEN }}

      - name: Cache NuGet
        uses: actions/cache@v5
        with:
          path: ~/.nuget/packages
          key: ${{ runner.os }}-nuget-${{ hashFiles('**/*.csproj') }}
          restore-keys: ${{ runner.os }}-nuget-

      - name: Compile
        run: dotnet run -c Release
        working-directory: .infrastructure/build
        env:
          INFRASTRUCTURE_PATH: ${{ github.workspace }}/.infrastructure
          PLUGIN_ROOT: ${{ github.workspace }}
          PLUGIN_CONFIG_PATH: ${{ github.workspace }}/plugin.config.json
          DOTNET_ENVIRONMENT: ${{ github.ref_name == 'main' && 'Production' || 'Development' }}
